# permissions for end users to edit graphscopeinsights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: graphscopeinsight-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: graphscope-insight-operator
    app.kubernetes.io/part-of: graphscope-insight-operator
    app.kubernetes.io/managed-by: kustomize
  name: graphscopeinsight-editor-role
rules:
- apiGroups:
  - insight.graphscope.io
  resources:
  - graphscopeinsights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insight.graphscope.io
  resources:
  - graphscopeinsights/status
  verbs:
  - get
