apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: graphscope-insight-operator
    app.kubernetes.io/part-of: graphscope-insight-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services", "events", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["insight.graphscope.io"]
  resources: ["graphscopeinsights", "graphscopeinsights/status", "graphscopeinsights/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
